parameters:
    locale: 'de'
    tei_dir: '%kernel.project_dir%/data/teis/'
    tei_sample_dir: '%kernel.project_dir%/data/sampletei/'
    lit_dir: '%kernel.project_dir%/data/lit/'
    gnd_files_dir: '%kernel.project_dir%/data/gnd-files/'
    wikidata_files_die:  '%kernel.project_dir%/data/wikidata-files/'
    wikipedia_files_die:  '%kernel.project_dir%/data/wikipedia-files/'
    geoname_files_dir: '%kernel.project_dir%/data/geoname-files/'
    tei_import_log_file: '%kernel.project_dir%/data/log/'
    document_languages:
        eng: Englisch
        fre: Französisch
        ger: Deutsch
        ita: Italienisch
        lat: Latein
    literatur_data_elements:
        biblScope_volume_n: biblScope_volume_n
        biblScope_part_n: biblScope_part_n
        biblScope_pages: biblScope_pages
        biblScope_part: biblScope_part
        biblScope_volume: biblScope_volume
        date: lit_pub_date
        extent: extent
        editor: editor
        edition: edition
        idno_isbn: ISBN
        idno_issn: ISSN
        title_a_main: analytic_main_title
        title_j_main: journal_main_title
        title_m_main: monographic_main_title
        title_s_main: series_main_title
        title_u_main: unpublished_main_title
        title_a_sub: analytic_sub_title
        title_j_sub: journal_sub_title
        title_m_sub: monographic_sub_title
        title_s_sub: series_sub_title
        title_u_sub: unpublished_sub_title

services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  Subugoe\TEI2SOLRBundle\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection}'

  Subugoe\TEI2SOLRBundle\Import\Importer:
    calls:
      - method: 'setConfigs'
        arguments:
          - '%tei_dir%'
          - '%tei_sample_dir%'
          - '%lit_dir%'
          - '%env(GITLAB_REPO_TOKEN)%'
          - '%env(GITLAB_REPO_TREE_URL)%'
          - '%env(GITLAB_PROCESSED_TEI_REPO_URL)%'
          - '%env(INVALIDE_TEI_LIST_FILE)%'
          - '%env(SAMPLE_TEI_DOCUMENT_URL)%'
          - '%env(GITLAB_LIT_REPO_URL)%'
          - '%env(GITLAB_PROCESSED_LIT_REPO_URL)%'
          - '%env(GITLAB_TEI_BRANCH_NAME)%'

  Subugoe\TEI2SOLRBundle\Index\Indexer:
    calls:
      - method: 'setConfigs'
        arguments:
          - '%tei_dir%'
          - '%tei_sample_dir%'
          - '%lit_dir%'
          - '%gnd_files_dir%'
          - '%geoname_files_dir%'
          - '%wikidata_files_die%'
          - '%wikipedia_files_die%'
          - '%tei_import_log_file%'
          - '%literatur_data_elements%'
          - '%env(INDEX_PAGES)%'
          - '%env(INDEX_ENTITIES)%'
          - '%env(INDEX_DOCTYPE_NOTES)%'
          - '%env(GND_API)%'
          - '%env(TRANSFORMATION_FIELDS)%'
          - '%env(INDEX_WIKIDATA)%'

  Subugoe\TEI2SOLRBundle\Transform\MetadataTransformer:
    calls:
      - method: 'setConfigs'
        arguments:
          - '%env(MAIN_DOMAIN)%'
          - '%document_languages%'

  Subugoe\TEI2SOLRBundle\Command\SolrIndexing:
    calls:
      - method: 'setConfigs'
        arguments:
          - '%env(IMPORT_SAMPLE_TEI)%'
          - '%env(IMPORT_TEI_FILES)%'
          - '%env(LITERATURE_TO_SOLR)%'
          - '%env(TEI_TO_SOLR)%'

